{"Message":"Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.","StackTrace":"   at System.Data.Entity.Internal.InternalContext.SaveChanges()\r\n   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()\r\n   at System.Data.Entity.DbContext.SaveChanges()\r\n   at Pajoohesh.Framework.Data.EF.DbContextCollection.Commit() in E:\\PajooheshWorkspace\\Framework\\Pajoohesh.Framework.Data.EF\\DbContextCollection.cs:line 64\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Pajoohesh.Framework.Data.EF.DbContextCollection.Commit() in E:\\PajooheshWorkspace\\Framework\\Pajoohesh.Framework.Data.EF\\DbContextCollection.cs:line 76\r\n   at Pajoohesh.Framework.Data.EF.DbContextScope.CommitInternal() in E:\\PajooheshWorkspace\\Framework\\Pajoohesh.Framework.Data.EF\\DbContextScope.cs:line 63\r\n   at Pajoohesh.Framework.Data.EF.DbContextScope.SaveChanges() in E:\\PajooheshWorkspace\\Framework\\Pajoohesh.Framework.Data.EF\\DbContextScope.cs:line 37\r\n   at Pajoohesh.Framework.Data.EF.UnitOfWork.SaveChanges() in E:\\PajooheshWorkspace\\Framework\\Pajoohesh.Framework.Data.EF\\UnitOfWork.cs:line 42\r\n   at Pajoohesh.UserManagement.BusinessService.UserService.GetUserLoginQuery(GetUserLoginQuery message) in E:\\PajooheshWorkspace\\TotalSystem\\Pajoohesh.UserManagement\\Pajoohesh.UserManagement.Service\\UserService.cs:line 205\r\n   at Pajoohesh.UserManagement.Agent.UserAgent.GetUserLoginQuery(GetUserLoginQuery message) in E:\\PajooheshWorkspace\\TotalSystem\\Pajoohesh.UserManagement\\Pajoohesh.UserManagement.Agent\\UserAgent.cs:line 38\r\n   at Pajoohesh.UserManagement.Web.Controllers.UserController.Login(GetUserLoginQuery userLoginRequest) in E:\\PajooheshWorkspace\\TotalSystem\\Pajoohesh.UserManagement\\Pajoohesh.UserManagement.Web\\Controllers\\UserController.cs:line 171\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerErrorStruct":null}
